"""QuikPlan output schema — field order must match app.py TABLE_SCHEMAS and QLA emit."""

QUIKACTG_SCHEMA = [
    "MCOMP", "MPLAN", "MPREM1ST", "MPREMREN", "MDIVCASH", "MDIVPREM", "MDIVACCM",
    "MDIVPUA", "MDIVPUT", "MDVDPINT", "MLOAN", "MLOANINT", "MSCHG", "MDEATH",
    "MCLAIM", "MCOM1ST", "MCOMREN", "MCOMMSGL",
]

QUIKPLAN_SCHEMA = [
    "PLAN", "FORM", "DESCR", "PAR", "SEX", "BASIS", "NFOINT", "LOANINT", "LOANINTX", "DEPINT",
    "VARDB", "VARGP", "LOAGE", "HIAGE", "RENEW", "PAYYRS", "PAYAGE", "INSYRS", "INSAGE",
    "ANNL", "SEMI", "QTRL", "MTHD", "MTHB", "ANNLFEE", "SEMIFEE", "QTRLFEE", "MTHDFEE", "MTHBFEE",
    "INITVAL", "MKTG", "PRODUCT", "CALCADV", "COMMID", "MINUNIT", "MAXUNIT", "BPOLFEE", "BACTIVE",
    "RRULE", "AGTRSV", "AUTONFO", "PLANTYPE", "INTMETHTV", "INTMETHCV", "DEFICIENCY", "HDEDMETHOD",
    "PLANVALOPT", "GDVARYGP", "GDVARYDB", "GDVARYCV", "GDVARYTV", "GDVARYDV",
    "UWVARYGP", "UWVARYDB", "UWVARYCV", "UWVARYTV", "UWVARYDV",
    "BDVARYGP", "BDVARYDB", "BDVARYCV", "BDVARYTV", "BDVARYDV",
    "STVARYGP", "STVARYDB", "STVARYCV", "STVARYTV", "STVARYDV",
    "CONVCOMM", "PLANNAME", "HRENEW", "HLOB", "HCOMMIP", "HRIGPKEY", "SIMPLEINT", "MLAPSE",
    "MNOTE10", "MNAICLOB", "MNFOANNV", "MGTDANNV",
]
